### ISSUE TITLE
 Possible Unhandled Promise Rejection (id: 0): ReferenceError: Can't find variable: failure

### ISSUE THREAD

**Issue by joshpitzalis** [georgelovegrove/graphcool-expo-auth0#1]
When I try and run this project I keep getting the error above. Is this happening to anyone else?

Ran the project in expo IDE, copied the project url into auth0, created graph.cool project, added the .env file, but no luck.

**Comment by lovegrovegeorge** [comment]
I've improved the README so check that for the Facebook login and test the auth0 connection works on Auth0. Remember to copy the URL to the .env file like mentioned in the documentation (https://github.com/graphcool-examples/react-native-graphql/tree/master/authentication-with-expo-and-auth0). The original documentation also mentions to add the auth0 allowed callback URLs in this format: exp://hw-pkc.georgelovegrove.PROJECT_NAME.exp.direct/+/redirect

**Comment by joshpitzalis** [comment]
changed 'failure' to 'error' and it solved the problem for me https://github.com/georgelovegrove/graphcool-expo-auth0/blob/master/src/auth/auth.js#L95

**Comment by lovegrovegeorge** [comment]
Fix pushed up, thanks
